### PR TITLE
Glide changes

### PR DESCRIPTION
**Pull request by TWiStErRob**
See bumptech/glide#1080

Remove jumpiness while loading
Show correct images
Wrap in cards to see groupings

### CODE REVIEW

**Comment by real-geekfan** [comment]
em..when scroll up/down and re-use view ,some `cardview` go blank(no Images inside).

**Comment by real-geekfan** [comment]
ah..just remove method `setImageUrls(null)`  from `onDetachedFromWindow` and that's ok.

**Comment by TWiStErRob** [comment]
Hmm, it was working for me always.
If you want to (and you should) free memory add in PhotoAdapter:

``` java
@Override public void onViewRecycled(ViewHolder vh) {
    vh.image.setImageUrls(null)
}
```

**Comment by real-geekfan** [comment]
that's right.It should be done to prevent OOM.

**Comment by TWiStErRob** [comment]
Not for OOM, because onBind reuses the views and calls setImageUrls, which I also changed to free resources. There would be only 1-2 extraneous items worth of images hidden in the background: this line clears those.

**Pull request merged**
